### ISSUE TITLE
Filament diameter not saving info on exit

### ISSUE THREAD

**Issue by RicXXX** [fieldOfView/Cura-MaterialSettingsPlugin#11]
Hello,
thanks for the plugin.

I've just updated Cura to 4.5.0
I've also installed the plugin "printer setting" that allowed me to change the filament diameter.

But with the new Cura release, the material setting plugin do not save (on exit from Cura) the "Diameter", so I cannot have a profile saved for any filament.
The other settings are saved.

Thanks to have a look.

**Comment by fieldOfView** [comment]
Aha! Thanks for those reproduction steps.

I have moved the issue back to the MaterialSettingsPlugin repo (sorry for my confusion there). I have reproduced the issue. There is an interesting issue going where it is possible to set the diameter both in the "Information" tab and in the "Print settings" tab. However, things are not working correctly either if you enter/change the diameter on the "Information" tab, so the fix may have to be in Cura instead of in this plugin. I will look in to it.

**Comment by RicXXX** [comment]
Thanks for your quick reply.
The information tab never worked. Diameter value there are not store (if you modify the diameter, close the tab and then open the tab again value is back at 1.75).
And I believe it is just a text field, without any effect on the printer setting nor the slicer.

Thanks for your time and effort.

**Comment by fieldOfView** [comment]
Could you try this [development snapshot](https://storage.googleapis.com/ultimaker-cura-packages/v1/packages/MaterialSettingsPlugin/BtcHgLp2SnzQrlL4QJGKU60xkwEJeOAB9yPI-7Y52WPS/MaterialSettingsPlugin-v7.0.0-2020-05-07T12%3A16%3A52Z.curapackage?Expires=1904213816&GoogleAccessId=cura-packages%40stardust-193112.iam.gserviceaccount.com&Signature=HwizHyfqhzrWZexd%2FakwemQTV9n8ExfDk44LiKkiALaTFNGn75Q3Yz5ZJhcpf%2BElr6dnlWzhOM0vD666qrS5823g%2Fthpf95Yyxb%2FLO9BrVDmHFkBnDu8Weo8mQR%2FPqVmRrcLL38JG5rkC8taNOov4RhyGp56p%2FTyU1%2FTy70Ne9v82CzPB9H96QB8HowMUSQpT0D2VrlHOXXiPGUXtH4eRPquHUo2NFoJ8gOrH84cCZ2xeyoHw6OkVRJywTX2Kc%2B6wssXBlUXWNYOQdrHmfzHeg6EThyEFtf3SNl7Iao8TRI5zMdbCVdVSEEbS2jvqKya765MVS6yFz0Ls6q20OrwVw%3D%3D)? Download the file, and drop it onto the Cura buildplate as if you were opening a 3d model.

It is no longer possible to show the "Diameter" setting in the "Print settings" tab, but the field in the "Information" tab should now work.

**Comment by RicXXX** [comment]
Installed (uninstall the standard version, reboot, install the downloaded file, reboot).
But it does NOT work.

Now the diameter setting is not available in the material printer setting tab (just to confirm I have installed the new version of the material setting plugin)
I open the material information tab and change the diameter.
But when I close and re-open the material information tab the diameter is back at 1.75.

I believe the material-information tab provide just information.
The printer setting are in the other tab (material-printer setting tab)
With the previous plugin version (the one available in the market) the material-printer setting tab was working: if I changed the diameter setting in the material-printer setting tab, the diameter was modified also in the slicer sidebar within the printer settings menu. 
The problem was that closing and re-opening Cura the diameter in the material-printer setting tab was not stored and back to the default value (1.75) 

P.S. it is important to see the diameter in the sidebar printer setting (or somewhere in the slicer) to verify that the slice is done with the right diameter setting

**Comment by fieldOfView** [comment]
> I believe the material-information tab provide just information.

It should be functional. When you enter a value in there, that value should carry over to the sidebar - *unless* there is a value "higher up" the settings stack (eg in the selected quality profile). 

There is a bug in Cura that makes the Diameter field on the Information tab not quite work, but for me the development snapshot fixes that bug. The Diameter value in the sidebar updates, and both the value in the sidebar and the Information tab stay the value I set them to. We have to find out why it does not work for you.

Could you try clicking into another field (eg the "Density" field) after you change the value? 
Another thing to try is using the up/down arrows on the right side of the field. If neither of those workarounds work, could you please zip up your entire configuration folder and send me a link at aldo(at)fieldofview(dot).com?

PS: The Diameter field in the Information tab has an additional important function: it warns the user when the material diameter is changed to a diameter that is incompatible with the current printer (eg a 2.85 mm diameter for a printer that uses 1.75 mm material). This is why I removed the functionality of having the Diameter field also available in the Print settings tab.

**Comment by RicXXX** [comment]
Looks to be SOLVED
>Could you try clicking into another field (eg the "Density" field) after you change the value?
&
> Another thing to try is using the up/down arrows on the right side of the field.
I was already using the arrows , it looks like this was the reason why it did not go into the slicer sidebar 
If I change the value writing in the field (or use the arrow and then highlight the same field value), the new value goes into the slicer sidebar menu and it is store in the material-information tab.
(Anyway I'm sure this was not the solution for the previous market version, because in the material-printer setting tab, the changed values were going to the slicer, but were not stored closing and re-opening Cura).

THANKS so much for your job, effort and time.
We solved the issue.

Will I receive update of the material setting plugin with the "beta" version installed or I will have to re-install it from the market?

P.S. In the multiple test I did, I noticed that if the Material is created using "duplicate" instead of "create" it is important to click the "Unlink the material" button, just below the warning "This material is linked to PLA and shares some of its properties".
Otherwise, even if the value is store in the material-information tab (with the procedure described above), it will not go in the slicer sidebar.

**Comment by fieldOfView** [comment]
Good to know you have a working solution, and thanks for the additional pointers to check out (linked materials and using the spinbox arrows). I’ll investigate both.

**Comment by fieldOfView** [comment]
> Will I receive update of the material setting plugin with the "beta" version installed or I will have to re-install it from the market?

Once a new release is "up" on the Marketplace, you will receive a notification in Cura that a new version is available just like it would be if you had not installed this development snapshot.

**Comment by RicXXX** [comment]
Thanks for the professional support.
Ciao
Ric

**Comment by fieldOfView** [comment]
I'm keeping this open to track the remaining couple of small things.

(it took me long enough to understand your issue properly...)

**Comment by RicXXX** [comment]
> I'm keeping this open to track the remaining couple of small things.
> (it took me long enough to understand your issue properly...)

Perfect.
If you need some tester I'm available.
