### ISSUE TITLE
Flow ratio not set in Cura 4.6.1

### ISSUE THREAD

**Issue by RobsonMi** [fieldOfView/Cura-MaterialSettingsPlugin#12]
Hello!

In Cura 4.6.1 Flow setting from material profile doesn't affect quality profile setting. Initial layer flow settings does work though. So it seems there is some change of xml param names? Can this be looked at?

Cheers.

**Comment by fieldOfView** [comment]
> In Cura 4.6.1 Flow setting from material profile doesn't affect quality profile setting.

This probably means that there is a value "higher up" in the setting stack that overrides what is set in the material. One of your quality profiles probably includes a value for the flow. The next version of the plugin will include a way to overrule the override. 

Can you save a project (File -> Save...) and post a link here so I can confirm this is the case?

**Comment by RobsonMi** [comment]
Hi! I went digging real quick and you are 100% right. Both profiles I use had flow setting. When removed it all works as advertised. Awesome job this plugin! And this override feature would be awesome to have. Also can you please think of a way to update material settings from main custom profile settings list? So that when flow, temp or whatever setting is adjusted instead of storing it in quality profile it gets stored in material profile, provided it's selected as material bound parameter? This would add a lot to workflow.

**Comment by fieldOfView** [comment]
> Awesome job this plugin!

Glad you like it.

> Also can you please think of a way to update material settings from main custom profile settings list?

No, because that is not how Cura works. I try not to fight against the architecture of Cura. All settings can be set (and have a place) in all of the levels of the settings stack.
