### ISSUE TITLE
No additional material settings ? (K-factor)

### ISSUE THREAD

**Issue by atsju** [fieldOfView/Cura-MaterialSettingsPlugin#15]
Hello, 
this is linked to https://github.com/fieldOfView/Cura-LinearAdvanceSettingPlugin/issues/30
I wanted the K-factor to be managed by material. I installed the plugin but only "flow" parameter has been added to print settings.
![image](https://user-images.githubusercontent.com/4628382/108601445-e93b4480-739c-11eb-9bca-bdecb470a245.png)
![image](https://user-images.githubusercontent.com/4628382/108601455-f6583380-739c-11eb-885c-7658970e5dde.png)
Is there anything special to do to add more parameters ? I found no documentation or tutorial on this setting so maybe I'm missing something obvious.

**Comment by fieldOfView** [comment]
See Extensions -> Material Settings -> Configure Material Settings. In that dialog you can select which settings will be visible in the Print Settings on the Materials pane of the preferences.

The next version of the pliugin will just add a button to select settings to be added to the specific material to the Print Settings on the Materials pane (similar to how Per Model Settings tool does it).

**Comment by atsju** [comment]
Thank you. It would be great to have this documented somewhere :)
