### ISSUE TITLE
The readme is very slim

### ISSUE THREAD

**Issue by charlespick** [fieldOfView/Cura-MaterialSettingsPlugin#17]
Hey, I want to use this plugin to store linear advance information for each of my filaments in Cura but I can't figure out how to use it. Where do you configure what settings are filament specific?

**Comment by fieldOfView** [comment]
Currently you configure that via `Extensions -> Material Settings -> Configure Material Settings`.

**Comment by fieldOfView** [comment]
The next version of this plugin will have a different way of "adding" settings to a material, directly from the materials preference pane instead of going through the Extensions menu. But there are still some hurdles to take for that change.

**Comment by fieldOfView** [comment]
Closed, since the instructions of how to add settings are now added to the readme.
