### ISSUE TITLE
"Select Settings" button is not visible in Cura 5.0 

### ISSUE THREAD

**Issue by Scotchy49** [fieldOfView/Cura-MaterialSettingsPlugin#22]
Plugin version: 3.6.0
Cura version: 5.0

The button is visible in Cura 4.13, but not in Cura 5.0.

**Comment by fieldOfView** [comment]
Just to confirm that you know the button is now in the material preferences dialog:
![](https://content.invisioncic.com/ultimake/monthly_2022_05/image.png.5624f0ab58308d9213bb1eb5e0b3fd54.png)

It could be that the plugin is not actually installed, even though Cura thinks (and shows) it is. Please try the following:
* In the Marketplace, uninstall the plugin
* Restart Cura (this is important!)
* In the Marketplace, reinstall the plugin
* Restart Cura again

Please let me know if this fixes it for you.

**Comment by Scotchy49** [comment]
Thanks, that worked!

I had previously reinstalled the plugin without restarting after uninstalling, and it did not work.

The step to restart Cura after uninstalling fixes the issue indeed.
