### ISSUE TITLE
Missing "Select settings" button in Cura 5.1.1

### ISSUE THREAD

**Issue by AlopexXx** [fieldOfView/Cura-MaterialSettingsPlugin#23]
The Plugin seems not to work in Cura 5.1.1

![image](https://user-images.githubusercontent.com/58085826/198368168-ca1078af-b468-4b48-8335-b523a01dcba4.png)

**Comment by fieldOfView** [comment]
Please try the following:
* In the Marketplace, go to the "manage" tab (the cog icon in the top right)
* Uninstall the Material Settings plugin
* Restart Cura (this is important!)
* Reinstall the plugin via the Marketplace
* Restart Cura again.

**Comment by AlopexXx** [comment]
This has helped.
Thank you :)
