### ISSUE TITLE
Manufacturer-supplied printer plugin completely messes with this plugin

### ISSUE THREAD

**Issue by evilC** [fieldOfView/Cura-MaterialSettingsPlugin#24]
Hi, apologies for posting this in an issue - I know that the problem that I am having is completely not your fault, but I am posting this in the hope that you may be able to give me some guidance.

I recently purchased a Snapmaker J1 IDEX printer, and they supplied a [plugin](https://github.com/Snapmaker/SnapmakerJ1CuraPlugin) to add support for it to Cura.

However, things are quirky with their plugin, to say the least.

Specifically, they have a load of settings for materials in the [quality profile](https://github.com/Snapmaker/SnapmakerJ1CuraPlugin/tree/main/resources/snapmaker_j1_profiles/quality/snapmaker_j1), and a whole host of other stuff going on  - the upshot being that even without using Material Settings, [print speed settings are greyed out](https://github.com/Snapmaker/SnapmakerJ1CuraPlugin/issues/30), it can [completely ignore the print temperature for a custom material](https://github.com/Snapmaker/SnapmakerJ1CuraPlugin/issues/28), etc, etc.

The same kind of stuff persists when trying to use your Material Settings plugin - it looks like it falls foul of this limitation of your plugin:
> This plugin does not change the fact that if a setting value is specified in the "sidebar" settings or in a quality profile, this always overrides the value set for the material

I was thinking of maybe trying to completely ditch their printer plugin and just add a custom printer myself, however the plugin does offer some stuff which may be desirable:
1. Sending jobs to the printer from cura via the [network](https://github.com/Snapmaker/SnapmakerJ1CuraPlugin/tree/main/network) - not something I would use for most jobs (I would use OctoPrint), but it's an IDEX printer, and I think the only way you can use "Mirror" or "Duplicate" modes is to send the STL to the printer (eg by using the "Send to printer" option in Cura) and then using the touchscreen on the printer to start that job in Mirror or Duplicate mode.
2. There appears to be some kind of [Gcode Translation](https://github.com/Snapmaker/SnapmakerJ1CuraPlugin/tree/main/gcode_writer) going on - looking at the code, I can tell certainly that one thing it does do in this code is pack a thumbnail of the print into the GCode for display on the screen of the printer, but I am unsure if it serves any other purpose.

Anyway, if you could offer any kind of advice as to how I may be able to get a more "Normal" workflow going for this printer, I would really appreciate it - I have an Ender 3 and use the Material Settings plugin quite happily with this printer - all I really want is for Cura for this printer to behave in the same way as it does with my existing printer.

**Comment by fieldOfView** [comment]
> all I really want is for Cura for this printer to behave in the same way as it does with my existing printer.

Well, it does... In "normal Cura", a setting defined in a quality profile overrides what is set in the material. The quality profiles that come with the plugin apparently have a lot of setting overrides in the quality profiles. 

What you can do is right-click on the setting in the settings bar and select the option to "Use value from material". This option is added by the Material Settings plugin.
