### ISSUE TITLE
Print speeds are not being applied

### ISSUE THREAD

**Issue by puregreen59** [fieldOfView/Cura-MaterialSettingsPlugin#25]
i have only cheaked print speed, top/bottom speed, and infill speed so far.

but nothing i change makes a diffrence, i can comfirm that changing it normally in my print settings profile works.

cheers!

**Comment by puregreen59** [comment]
Please forgive me! i've fixed it,

for anyone else with this issue, 

go to your print setting profile.

right click the offending setting and choose 

"use value from material"

**Comment by aqc-carlodri** [comment]
Thanks! Found this reply after a lot of searching on this issue. @fieldOfView I think it would be worth mentioning this in the README file, WDYT?

**Comment by levydanqc** [comment]
Yes please mention this in the README file... @fieldOfView 
Spent way too much time trying to make a working plugins... work!

That's crucial informations 🙃
