### ISSUE TITLE
Missing retraction settings from KlipperSettings plugin

### ISSUE THREAD

**Issue by leoshusar** [fieldOfView/Cura-MaterialSettingsPlugin#26]
I wanted to use firmware retraction and set different distance / speed per material.
However I don't see these options here:
![image](https://user-images.githubusercontent.com/13891066/214966865-51eea57a-095d-47be-88a6-5fa8fa0eed3a.png)

Did I miss something or is this a bug?

**Comment by fieldOfView** [comment]
Not all settings can have a value in a material in Cura. Settings need to be marked as "settable_per_extruder", or they need to have a "resolve" function. A resolve function tells Cura what setting to use for a global setting coflicts between multiple extruders (such as for example the bed temperature, which can not have two values at the same time).

It would be my guess that the settings for the KlipperSettings plugin that you mention are neither defined as "settable_per_extruder" not do they have a "resolve" function.

**Comment by leoshusar** [comment]
Thanks for the explanation! I checked it and indeed they miss those attributes.
