### ISSUE TITLE
Hard to open Manage Materials Preferences

### ISSUE THREAD

**Issue by MariMakes** [fieldOfView/Cura-MaterialSettingsPlugin#29]
**Plugin Version**
MaterialSettingsPlugin 3.6.0.

**Operating System**
Windows 10

**Reproduction Steps**
https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/assets/40423138/54e7bd63-d512-45cb-bafe-da29cff31447

**Context**
[We received this issue for Cura 5.5 beta:](https://community.ultimaker.com/topic/44294-ultimaker-cura-55-beta-released/?do=findComment&comment=326268)

> The Preferences dialog does not configure to "Manage Materials".  I was able to get the Material list loaded by opening a project file. The dialog is always "whatever the last subject was" rather than Materials. If you look closely you will see that the "Defaults" button is actually displaced from the button below.  The amount of displacement varies, but I can always see two (maybe three) buttons on top of each other.

**Actual Result**
Hard to open Manage Materials Preferences. We had some trouble reproducing the issue, but when we received the configuration folder of @GregValiant we learned that we could restore the original behavior by disabling the MaterialSettingsPlugin 3.6.0.

If you need any help from the Cura developers, please let me know 😉

**Comment by fieldOfView** [comment]
The patched Materials pane fails to load because of the removal of the Cura.ColorDialog. One could argue that that removal is an SDK break. 

I will work around it on my side and post an update asap.

**Comment by MariMakes** [comment]
Oh! I wasn't aware. 😮 
I'll let the team know as well. 💪

**Comment by fieldOfView** [comment]
For my reference: https://github.com/Ultimaker/Cura/commit/9407345377bf0479148308dbbe3ae2c7797b9724

**Comment by fieldOfView** [comment]
This is fixed in the above lined commit, but there's still some backlash from another recent change on my side (20452844c295f381fed734a97c7672638878e55f) which prevents me from releasing a dev version of the fix.

**Comment by MariMakes** [comment]
@wawanbreton also made a change here: https://github.com/Ultimaker/Cura/pull/17037
I hope this helps 😇

**Comment by wawanbreton** [comment]
The commit that actually helps is actually this one: https://github.com/Ultimaker/Cura/commit/0ff069a8dd2a3c2a8262cd83456113218a666cb5
Sorry I made a mistake and commited it outside of the branch :angel: 
Anyway, they are both in the 5.5 branch now.

**Comment by fieldOfView** [comment]
A version that does not use the previously removed, now deprecated ColorDialog is available for testing here:
https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/releases/tag/v3.6.1-DEV
This one works with the 5.5 beta 1 (and upcoming 5.5 releases).
