### ISSUE TITLE
(4.2.1) Material not switchable

### ISSUE THREAD

**Issue by Ex0ry** [fieldOfView/Cura-MaterialSettingsPlugin#3]
Hello there again,
The latest version of the plugin worked quite pleasing with Cura 4.0.
However, when Cura 4.2.1 came out, it was time to update.
Quickly i noticed a little bug in the "Manage Materials" menu ,which stopped me from switching materials in the Menu. 
It isn't that big of a deal, since the material is still changeable through the normal drop-down menu while preparing the model, but it is still annoying.
The Problem does not occur when the Plugin is uninstalled..

**Comment by fieldOfView** [comment]
Issue is caused by https://github.com/Ultimaker/Cura/commit/914d2e98e977131b67a85131ba29aadf63fb4f91#diff-7350e9d08a06d9246ab8a568e3becc2b which is in 4.2.1, but not yet in 4.2. I will push a new release to the Marketplace.
