### ISSUE TITLE
Selecting material does not update the settings in the edit dialog

### ISSUE THREAD

**Issue by awabom** [fieldOfView/Cura-MaterialSettingsPlugin#30]
In Cura 5.5.0 with today's(?) updated plugin version, the materials dialog seems to display again, but does not work properly.

When opening from e.g. extruder 2 - "Manage materials...", that extruder's current material is shown in the dialog. Then, if I select another material, the values are still from the first shown material - not the newly selected one.

Switching from a preset material to a custom material enables editing of all values, but the values are still from the initial material.

**Comment by awabom** [comment]
Version tested was 3.6.1

**Comment by juricabi** [comment]
Same problem here also, cura 4.2, version of plugin 3.6.1

**Comment by fieldOfView** [comment]
Should be fixed in 603a244

Please help testing the fix by installing this prerelease:
https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/releases/tag/v3.6.2-DEV

Download the curapackage appropriate for your version of Cura and drop the file onto the buildplate as if you were opening a 3d model. Then restart Cura as instructed.

**Comment by BremerButjer** [comment]
> Should be fixed in [603a244](https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/commit/603a244abdcadb473bf43276282fe867621c4d58)
> 
> Please help testing the fix by installing this prerelease: https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/releases/tag/v3.6.2-DEV
> 
> Download the curapackage appropriate for your version of Cura and drop the file onto the buildplate as if you were opening a 3d model. Then restart Cura as instructed.

Tested with Cura 5.5. Works fine!

**Comment by juricabi** [comment]
> Should be fixed in [603a244](https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/commit/603a244abdcadb473bf43276282fe867621c4d58)
> 
> Please help testing the fix by installing this prerelease: https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/releases/tag/v3.6.2-DEV
> 
> Download the curapackage appropriate for your version of Cura and drop the file onto the buildplate as if you were opening a 3d model. Then restart Cura as instructed.

Tested in 4.2, works good.

**Comment by awabom** [comment]
Confirmed working in 5.5.0 :)

**Comment by fieldOfView** [comment]
Thanks for testing. I'll keep this issue open until a fixed release is available in the Marketplace, so others can find the issue and the fix more easily.
