### ISSUE TITLE
Flow not updated when using non-default profile

### ISSUE THREAD

**Issue by silvio3105** [fieldOfView/Cura-MaterialSettingsPlugin#32]
Hi,
material flow is not updated from material settings when non-default print settings profile is used.
Elegoo Cura 4.8.0-230905.0 with v3.6.2 plugin, custom material.

**Comment by fieldOfView** [comment]
From the [readme](https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/blob/release/README.md):

> This plugin does not change the fact that if a setting value is specified in the "sidebar" settings or in a quality profile, this always overrides the value set for the material.

You can right-click the setting in the "sidebar" and select "use value from material".
