### ISSUE TITLE
Some settings are missing from option to be set in the materials

### ISSUE THREAD

**Issue by vasilp** [fieldOfView/Cura-MaterialSettingsPlugin#34]
As example:

- Enable Draft Shield
- Enable Print Cooling

**Comment by fieldOfView** [comment]
Correct. Some settings can not be set per extruder, so in Cura they can not be set per material. This is a limitation of how settings work in Cura.

Technically, settings either need to be "settable_per_extruder", or they need to have a "resolve" function.
