### ISSUE TITLE
Plugin no longer work with Cura 4.4

### ISSUE THREAD

**Issue by chjohans** [fieldOfView/Cura-MaterialSettingsPlugin#5]
As the topic says this plugin no longer works with Cura 4.4. I'm totally dependent on this excellewnt plugin so please fix this if possible. :)

**Comment by fieldOfView** [comment]
@sharkovich had already done the work here: https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/pull/4

I had to make sure that the plugin also works for Cura 3.5-4.3; I can only publish a single version of the plugin that should be compatible with all versions, or the plugin will become unavailable for all older versions of Cura.

A version that is compatible with Cura 4.4 is now awaiting approval for the Marketplace.
