### ISSUE TITLE
MaterialsPage.qml still uses CuraApplication.getMaterialManager

### ISSUE THREAD

**Issue by bredeker** [fieldOfView/Cura-MaterialSettingsPlugin#7]
After installing this plug-in on Cura 4.4, I noticed I was not able to duplicate Material profiles, and the following was logged when I clicked the respective button:

`2019-12-23 00:19:16,951 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [369]: file:[…]/cura/4.4/plugins/MaterialSettingsPlugin/MaterialSettingsPlugin/qml/MaterialPreferences/MaterialsPage.qml:132: TypeError: Property 'getMaterialManager' of object CuraApplication(0x600003ce43c0) is not a function`

Based on PR #4, it looks like getMaterialManager was removed in the latest API, but the references to it in MaterialsPage.qml were missed. I was able to fix the problem (from what I can tell) by duplicating the `materialManager` property definition from commit 87655d2df11ae35a0ffe4f22b2ac0e97d82914c7 and replacing calls to `CuraApplication.getMaterialManager` with calls to that property. Redundant declarations across the two files do not seem like a good long-term fix, so I do not think my hack has good value as a PR. I have no prior experience with QML and am not sure what the best practice is, so I thought I would at least submit the issue and let a more experienced hand craft an official solution.

**Comment by fieldOfView** [comment]
Good catch. This causes https://github.com/Ultimaker/Cura/issues/6864

The complication in fixing this, is that the plugin must also still work with previous versions of Cura. I'll get on it.

**Comment by fieldOfView** [comment]
This should be fixed in https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/commit/9ca0c6d0be2c7cf21ab7944d6163f04a9571dfe0
