### ISSUE TITLE
Linear advance support 

### ISSUE THREAD

**Issue by Anarasha** [fieldOfView/Cura-MaterialSettingsPlugin#8]
Not technically an issue as much as a request. 
Linear Advance is becoming increasingly popular, so if at all possible it would be amazing to have a material setting for the K factor :D 

Other than that, amazing plugin, thank you!

**Comment by fieldOfView** [comment]
You are in luck: There's a plugin for Linear Advance in the Marketplace (written by... me). Once you've installed that, you can add the Linear Advance factor to the Print Settings on the Material pane using Extensions -> Material Settings -> Configure Material Settings

**Comment by Anarasha** [comment]
Aah, thank you so much! :D I had no idea, this is awesome
